version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: petsdb
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./mock_data:/import_data
    networks:
      - bigdata

  spark-master:
    build:
      context: .
      dockerfile: ./spark/Dockerfile
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_NO_DAEMONIZE=yes
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark:/opt/spark-apps
      - ./jars:/opt/spark/jars
    depends_on:
      - postgres
      - mongodb
    networks:
      - bigdata

  spark-worker:
    build:
      context: .
      dockerfile: ./spark/Dockerfile
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=yes
    depends_on:
      - spark-master
      - mongodb
    volumes:
      - ./spark:/opt/spark-apps
      - ./jars:/opt/spark/jars
    networks:
      - bigdata

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - bigdata

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    networks:
      - bigdata

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bigdata

volumes:
  pgdata:
  mongo_data:

networks:
  bigdata:
    driver: bridge